#!/usr/bin/bash

M=2500
N=2500
K=2500

# use ninja if installed
build_tool=""
if [ -f "/usr/bin/ninja" ]; then
    build_tool="-G Ninja"
fi

# build
cmake -B build $build_tool -DKokkos_ENABLE_OPENMP=ON -DCMAKE_BUILD_TYPE=Release
cmake --build ./build --config Release || exit

# run
export OMP_PROC_BIND=true
export OMP_PLACES=cores
rm -f out.txt

MAX_THREADS=$(lscpu -p | egrep -v '^#' | sort -u -t, -k 2,4 | wc -l)

for i in $(seq 1 $MAX_THREADS)
do
    export OMP_NUM_THREADS=$i
    build/src/top.matrix_product $M $N $K  >> out.txt
done

# report
python3 main_comparaison.py $M $N $K || exit